-- =====================================================================
-- ANA CLARA NAILS — SCHEMA CANÔNICO (PostgreSQL 16)
-- Padrão empresarial:
--   * tabelas em snake_case minúsculo, PK IDENTITY
--   * auditoria created_at / updated_at em todas as tabelas de domínio
--   * FKs nomeadas (fk_<tabela>_<coluna>), índices nas colunas de junção
--   * UNIQUE nas chaves naturais, seeds versionados no final
-- Fonte única de verdade do modelo. Migrações incrementais em back/migrations/.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TIPOS DE USUÁRIO (papéis: ADMIN / USER)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "type_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(30) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 2. USUÁRIOS (login do sistema)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "usuarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT NOT NULL
        CONSTRAINT "fk_usuarios_type_user_id"
        REFERENCES "type_users" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_usuarios_type_user_id"
    ON "usuarios" ("type_user_id");

-- ---------------------------------------------------------------------
-- 3. CLIENTES
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "clientes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "telefone" VARCHAR(30),
    "email_id" BIGINT
        CONSTRAINT "fk_clientes_email_id"
        REFERENCES "usuarios" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_clientes_email_id"
    ON "clientes" ("email_id");
CREATE INDEX IF NOT EXISTS "ix_clientes_nome"
    ON "clientes" ("nome");

-- ---------------------------------------------------------------------
-- 4. PROFISSIONAIS (nail designers)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "nail_designs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "telefone" VARCHAR(30),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 5. ADMINISTRADORES (profissional responsável pelo painel)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "administradores" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT NOT NULL
        CONSTRAINT "fk_administradores_type_user_id"
        REFERENCES "type_users" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "nail_design_id" BIGINT
        CONSTRAINT "fk_administradores_nail_design_id"
        REFERENCES "nail_designs" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_administradores_nail_design_id"
    ON "administradores" ("nail_design_id");

-- ---------------------------------------------------------------------
-- 6. MODELOS DE UNHA (catálogo — imagem servida via Cloudflare R2)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "modelos_unhas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL UNIQUE,
    "valor_total" NUMERIC(10, 2) NOT NULL,
    "categoria" VARCHAR(50),
    "descricao" TEXT,
    "duracao" TIME,
    "imagem_url" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_modelos_unhas_categoria"
    ON "modelos_unhas" ("categoria");

-- ---------------------------------------------------------------------
-- 7. PROGRAMAÇÃO SEMANAL (agenda da profissional)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "programacao_semanal" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profissional_id" BIGINT NOT NULL
        CONSTRAINT "fk_programacao_semanal_profissional_id"
        REFERENCES "nail_designs" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE,
    "dia_semana" VARCHAR(20) NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "inicio_expediente" TIME,
    "fim_expediente" TIME,
    "pausa_duracao" TIME,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_programacao_semanal_profissional_dia"
        UNIQUE ("profissional_id", "dia_semana")
);
CREATE INDEX IF NOT EXISTS "ix_programacao_semanal_profissional_id"
    ON "programacao_semanal" ("profissional_id");

-- ---------------------------------------------------------------------
-- 8. STATUS DE PAGAMENTO
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "status_pagamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(30) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 9. AGENDAMENTOS
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "agendamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cliente_id" BIGINT NOT NULL
        CONSTRAINT "fk_agendamentos_cliente_id"
        REFERENCES "clientes" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "modelo_id" BIGINT NOT NULL
        CONSTRAINT "fk_agendamentos_modelo_id"
        REFERENCES "modelos_unhas" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "horario" TIME NOT NULL,
    "sinal" NUMERIC(10, 2) NOT NULL,
    "status_pagamentos_id" BIGINT
        CONSTRAINT "fk_agendamentos_status_pagamentos_id"
        REFERENCES "status_pagamentos" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_agendamentos_cliente_id"
    ON "agendamentos" ("cliente_id");
CREATE INDEX IF NOT EXISTS "ix_agendamentos_status_pagamentos_id"
    ON "agendamentos" ("status_pagamentos_id");
CREATE INDEX IF NOT EXISTS "ix_agendamentos_horario"
    ON "agendamentos" ("horario");

-- ---------------------------------------------------------------------
-- 10. NOTIFICAÇÕES DO PAINEL (sino da admin)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "notificacoes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" VARCHAR(30) NOT NULL,
    "titulo" VARCHAR(150) NOT NULL,
    "mensagem" TEXT NOT NULL,
    "agendamento_id" BIGINT
        CONSTRAINT "fk_notificacoes_agendamento_id"
        REFERENCES "agendamentos" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "lida" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "ck_notificacoes_tipo" CHECK (
        "tipo" IN ('agendamento', 'cancelamento', 'pagamento', 'mensagem')
    )
);
CREATE INDEX IF NOT EXISTS "ix_notificacoes_lida"
    ON "notificacoes" ("lida");
CREATE INDEX IF NOT EXISTS "ix_notificacoes_created_at"
    ON "notificacoes" ("created_at" DESC);

-- ---------------------------------------------------------------------
-- 11. INSCRIÇÕES WEB PUSH (dispositivos logados da admin)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "endpoint" TEXT NOT NULL UNIQUE,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- SEEDS (idempotentes — alinhados aos enums do backend)
--   TypeUserEnum: ADMIN = 1, USER = 2
--   StatusPagamentoEnum: Pendente, Pago, Cancelado
-- =====================================================================
INSERT INTO "type_users" ("id", "nome") VALUES
    (1, 'ADMIN'),
    (2, 'USER')
ON CONFLICT ("id") DO UPDATE SET
    "nome" = EXCLUDED."nome",
    "updated_at" = now();

INSERT INTO "status_pagamentos" ("nome") VALUES
    ('Pendente'),
    ('Pago'),
    ('Cancelado')
ON CONFLICT ("nome") DO NOTHING;
