--
-- PostgreSQL database dump
--

\restrict 9yc20c9gAeFUbITaU235JpNQnk8ffjccbXqGpD53FKN0RSjJL1mUdhuCgqlcrvs

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administradores; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.administradores (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    type_user_id bigint,
    nail_design_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.administradores OWNER TO nail_admin;

--
-- Name: administradores_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.administradores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administradores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agendamentos; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.agendamentos (
    id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    modelo_id bigint NOT NULL,
    horario time without time zone NOT NULL,
    sinal numeric(10,2) NOT NULL,
    status_pagamentos_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    data date
);


ALTER TABLE public.agendamentos OWNER TO nail_admin;

--
-- Name: agendamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.agendamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agendamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bloqueios; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.bloqueios (
    id bigint NOT NULL,
    data date NOT NULL,
    motivo character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.bloqueios OWNER TO nail_admin;

--
-- Name: bloqueios_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.bloqueios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bloqueios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    telefone character varying(30),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    molde text,
    cpf character varying(14),
    data_nascimento date,
    pref_app boolean DEFAULT true NOT NULL,
    pref_email boolean DEFAULT true NOT NULL,
    pref_whatsapp boolean DEFAULT false NOT NULL,
    email_id bigint
);


ALTER TABLE public.clientes OWNER TO nail_admin;

--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagens; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.mensagens (
    id bigint NOT NULL,
    agendamento_id bigint,
    remetente character varying(20) DEFAULT 'admin'::character varying NOT NULL,
    texto text NOT NULL,
    lida boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_mensagens_remetente CHECK (((remetente)::text = ANY ((ARRAY['admin'::character varying, 'cliente'::character varying])::text[])))
);


ALTER TABLE public.mensagens OWNER TO nail_admin;

--
-- Name: mensagens_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.mensagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modelos_unhas; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.modelos_unhas (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    valor_total numeric(10,2),
    categoria character varying(50),
    descricao text,
    duracao time without time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    imagem_url text,
    ativo boolean DEFAULT true NOT NULL,
    destaque boolean DEFAULT false NOT NULL
);


ALTER TABLE public.modelos_unhas OWNER TO nail_admin;

--
-- Name: modelos_unhas_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.modelos_unhas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modelos_unhas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nail_designs; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.nail_designs (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    cpf character varying(14) NOT NULL,
    telefone character varying(30),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.nail_designs OWNER TO nail_admin;

--
-- Name: nail_designs_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.nail_designs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nail_designs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificacoes; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.notificacoes (
    id bigint NOT NULL,
    tipo character varying(30) NOT NULL,
    titulo character varying(150) NOT NULL,
    mensagem text NOT NULL,
    agendamento_id bigint,
    lida boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_notificacoes_tipo CHECK (((tipo)::text = ANY ((ARRAY['agendamento'::character varying, 'cancelamento'::character varying, 'pagamento'::character varying, 'mensagem'::character varying])::text[])))
);


ALTER TABLE public.notificacoes OWNER TO nail_admin;

--
-- Name: notificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.notificacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.password_resets (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    usado_em timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.password_resets OWNER TO nail_admin;

--
-- Name: password_resets_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.password_resets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_resets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: programacao_semanal; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.programacao_semanal (
    id bigint NOT NULL,
    profissional_id bigint,
    dia_semana character varying(20),
    ativo boolean DEFAULT true NOT NULL,
    inicio_expediente time without time zone,
    fim_expediente time without time zone,
    pausa_duracao time without time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    intervalo_minutos integer DEFAULT 90 NOT NULL
);


ALTER TABLE public.programacao_semanal OWNER TO nail_admin;

--
-- Name: programacao_semanal_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.programacao_semanal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programacao_semanal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: push_subscriptions; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.push_subscriptions (
    id bigint NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.push_subscriptions OWNER TO nail_admin;

--
-- Name: push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status_pagamentos; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.status_pagamentos (
    id bigint NOT NULL,
    nome character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.status_pagamentos OWNER TO nail_admin;

--
-- Name: status_pagamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.status_pagamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_pagamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_users; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.type_users (
    id bigint NOT NULL,
    nome character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.type_users OWNER TO nail_admin;

--
-- Name: type_users_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.type_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: nail_admin
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nome character varying(100),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    type_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.usuarios OWNER TO nail_admin;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: nail_admin
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: administradores; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.administradores (id, nome, email, password, type_user_id, nail_design_id, created_at, updated_at) FROM stdin;
1	Ana Clara	ana.clara@nails.com	$argon2id$v=19$m=65536,t=3,p=4$CZ2xNkgPg62bowKdMTN8Dg$Mdf0lObLFYJo/mTfBtAcjYPOG9NDkrdvPKCD5nm9BIc	1	1	2026-09-12 16:16:06.053873+00	2026-09-12 16:16:06.053873+00
\.


--
-- Data for Name: agendamentos; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.agendamentos (id, cliente_id, modelo_id, horario, sinal, status_pagamentos_id, created_at, updated_at, data) FROM stdin;
9	8	1	10:30:00	50.00	2	2026-09-13 04:10:24.131785+00	2026-09-13 04:10:24.131785+00	2026-09-14
10	8	1	13:30:00	50.00	2	2026-09-13 04:40:17.528585+00	2026-09-13 04:40:17.528585+00	2026-09-15
\.


--
-- Data for Name: bloqueios; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.bloqueios (id, data, motivo, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.clientes (id, nome, telefone, created_at, updated_at, molde, cpf, data_nascimento, pref_app, pref_email, pref_whatsapp, email) FROM stdin;
8	Ms Mariaeduarda6755	61981741089	2026-09-13 04:09:52.15538+00	2026-09-13 04:09:52.15538+00	\N	\N	\N	t	t	f	\N
9	Teste Mask ad52	61998174108	2026-09-13 04:20:34.46156+00	2026-09-13 04:20:34.46156+00	\N	52998224725	\N	t	t	f	\N
\.


--
-- Data for Name: mensagens; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.mensagens (id, agendamento_id, remetente, texto, lida, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: modelos_unhas; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.modelos_unhas (id, nome, valor_total, categoria, descricao, duracao, created_at, updated_at, imagem_url, ativo, destaque) FROM stdin;
1	Teste Fibra	100.00	alongamento	teste	01:30:00	2026-09-12 03:41:11.665077+00	2026-09-12 03:41:11.665077+00	\N	t	f
2	Francesinha Lilás	100.00	Clássicas	Clássica com ponta lilás	01:00:00	2026-09-12 15:12:56.993622+00	2026-09-12 15:12:56.993622+00	\N	f	t
\.


--
-- Data for Name: nail_designs; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.nail_designs (id, nome, cpf, telefone, created_at, updated_at) FROM stdin;
1	Ana Clara	12345678909	(11) 90000-0000	2026-09-12 15:12:40.537943+00	2026-09-12 15:12:40.537943+00
\.


--
-- Data for Name: notificacoes; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.notificacoes (id, tipo, titulo, mensagem, agendamento_id, lida, created_at, updated_at) FROM stdin;
1	agendamento	Novo agendamento recebido	Agendamento #1 criado e aguardando o sinal.	\N	f	2026-09-12 03:42:22.097581+00	2026-09-12 03:42:22.097581+00
2	agendamento	Novo agendamento recebido	Agendamento #2 criado e aguardando o sinal.	\N	f	2026-09-12 04:43:58.360202+00	2026-09-12 04:43:58.360202+00
3	agendamento	Novo agendamento recebido	Agendamento #3 criado e aguardando o sinal.	\N	f	2026-09-12 04:46:57.928774+00	2026-09-12 04:46:57.928774+00
4	pagamento	Sinal pago com sucesso	Sinal do agendamento #3 aprovado.	\N	f	2026-09-12 04:46:59.59928+00	2026-09-12 04:46:59.59928+00
5	agendamento	Novo agendamento recebido	Agendamento #4 criado e aguardando o sinal.	\N	f	2026-09-12 05:00:36.888656+00	2026-09-12 05:00:36.888656+00
9	agendamento	Novo agendamento recebido	Agendamento #6 criado e aguardando o sinal.	\N	f	2026-09-12 05:04:04.763203+00	2026-09-12 05:04:04.763203+00
10	pagamento	Sinal pago com sucesso	Sinal do agendamento #6 aprovado.	\N	f	2026-09-12 05:04:07.940829+00	2026-09-12 05:04:07.940829+00
11	pagamento	Sinal pago com sucesso	Sinal do agendamento #6 aprovado.	\N	f	2026-09-12 05:04:09.020668+00	2026-09-12 05:04:09.020668+00
12	agendamento	Novo agendamento recebido	Agendamento #7 criado e aguardando o sinal.	\N	f	2026-09-12 05:06:37.974069+00	2026-09-12 05:06:37.974069+00
6	agendamento	Novo agendamento recebido	Agendamento #5 criado e aguardando o sinal.	\N	f	2026-09-12 05:01:31.694154+00	2026-09-12 05:01:31.694154+00
7	pagamento	Sinal pago com sucesso	Sinal do agendamento #5 aprovado.	\N	f	2026-09-12 05:01:34.48309+00	2026-09-12 05:01:34.48309+00
8	pagamento	Sinal pago com sucesso	Sinal do agendamento #5 aprovado.	\N	f	2026-09-12 05:01:44.723833+00	2026-09-12 05:01:44.723833+00
13	pagamento	Sinal pago com sucesso	Sinal do agendamento #5 aprovado.	\N	f	2026-09-12 05:21:00.47941+00	2026-09-12 05:21:00.47941+00
14	agendamento	Novo agendamento recebido	Agendamento #8 criado e aguardando o sinal.	\N	f	2026-09-12 05:41:57.037248+00	2026-09-12 05:41:57.037248+00
15	agendamento	Novo agendamento recebido	Agendamento #9 criado e aguardando o sinal.	9	f	2026-09-13 04:10:24.164502+00	2026-09-13 04:10:24.164502+00
16	agendamento	Novo agendamento recebido	Agendamento #10 criado e aguardando o sinal.	10	f	2026-09-13 04:40:17.542566+00	2026-09-13 04:40:17.542566+00
\.


--
-- Data for Name: password_resets; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.password_resets (id, usuario_id, token_hash, expira_em, usado_em, created_at, updated_at) FROM stdin;
1	6	a7e5767cf03de782868dc68c64f4665ed6219a00163801d647f289616d330038	2026-09-12 16:25:27.843626+00	\N	2026-09-12 15:55:27.844879+00	2026-09-12 15:55:27.844879+00
2	6	b5f412d1fb66db70f06a9944e7d49925a6bdbdb84c6ade141c4f59f598fec9bd	2026-09-12 16:27:54.41573+00	2026-09-12 15:57:54.683726+00	2026-09-12 15:57:54.41573+00	2026-09-12 15:57:54.41573+00
\.


--
-- Data for Name: programacao_semanal; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.programacao_semanal (id, profissional_id, dia_semana, ativo, inicio_expediente, fim_expediente, pausa_duracao, created_at, updated_at, intervalo_minutos) FROM stdin;
1	1	Segunda	t	09:00:00	18:00:00	01:00:00	2026-09-12 15:12:40.545576+00	2026-09-12 15:12:40.545576+00	90
2	1	Terça	t	09:00:00	18:00:00	01:00:00	2026-09-12 15:12:40.545576+00	2026-09-12 15:12:40.545576+00	90
3	1	Quarta	t	09:00:00	18:00:00	01:00:00	2026-09-12 15:12:40.545576+00	2026-09-12 15:12:40.545576+00	90
4	1	Quinta	t	09:00:00	18:00:00	01:00:00	2026-09-12 15:12:40.545576+00	2026-09-12 15:12:40.545576+00	90
5	1	Sexta	t	09:00:00	18:00:00	01:00:00	2026-09-12 15:12:40.545576+00	2026-09-12 15:12:40.545576+00	90
\.


--
-- Data for Name: push_subscriptions; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.push_subscriptions (id, endpoint, p256dh, auth, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: status_pagamentos; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.status_pagamentos (id, nome, created_at, updated_at) FROM stdin;
1	Cancelado	2026-09-12 03:06:51.595733+00	2026-09-12 03:06:51.595733+00
2	Pendente	2026-09-12 03:06:51.595733+00	2026-09-12 03:06:51.595733+00
3	Pago	2026-09-12 03:06:51.595733+00	2026-09-12 03:06:51.595733+00
\.


--
-- Data for Name: type_users; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.type_users (id, nome, created_at, updated_at) FROM stdin;
1	ADMIN	2026-09-12 03:05:16.404638+00	2026-09-13 04:51:30.217756+00
2	USER	2026-09-12 03:05:16.404638+00	2026-09-13 04:51:30.217756+00
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: nail_admin
--

COPY public.usuarios (id, nome, email, password, type_user_id, created_at, updated_at) FROM stdin;
1	\N	teste@pagamento.com	Teste123!	2	2026-09-12 03:37:02.481719+00	2026-09-12 03:37:02.481719+00
2	\N	teste2@pagamento.com	$argon2id$v=19$m=65536,t=3,p=4$oc27lT3y8Avzwgw0jkh/CA$fOwM4SxzL4GTP9u/nOeakTuxTbMjl6eFRD/qOmvTKiU	2	2026-09-12 03:39:16.971817+00	2026-09-12 03:39:16.971817+00
3	\N	admin@pagamento.com	$argon2id$v=19$m=65536,t=3,p=4$jMrF+Fy0d9UV4SrmEVCxIw$OOedMKFhGc74ALWrk/cT/jFbkfuqwftV1h0hSxF4r1I	1	2026-09-12 03:41:11.460635+00	2026-09-12 03:41:11.460635+00
4	\N	semhash@teste.com	$argon2id$v=19$m=65536,t=3,p=4$7sRdQFIdy2eQCtzPhkLEMA$OMm/IFdQwCA8IeRyjTFbJhi8PBbDi6RZkyWDzHiVP3A	2	2026-09-12 05:29:13.323016+00	2026-09-12 05:29:13.323016+00
5	Ana Clara	ana.clara@anaclaranails.com	$argon2id$v=19$m=65536,t=3,p=4$7tldMLhdPlpc2bMk9N2BDQ$XoXXyGjEMGe9yYD9rhvFrBWv7Gk65hosV1utuBAOGxQ	1	2026-09-12 15:12:40.524821+00	2026-09-12 15:12:40.524821+00
6	\N	smoke@prod.com	$argon2id$v=19$m=65536,t=3,p=4$/grFypqpu3thBYdpWDvRag$CZaoMLwPhOaC1eGTJtqcCnxMOfH08CqUitIQu98gJlI	2	2026-09-12 15:23:31.49182+00	2026-09-12 15:23:31.49182+00
7	Ana Clara	seed@prod.com	$argon2id$v=19$m=65536,t=3,p=4$oZOopHmqHCGak87SNm5b6g$jovdyKRZmTf/Byzue/lXdRr9wX3ZqE72VaHv9dEYphw	1	2026-09-12 15:59:05.607127+00	2026-09-12 15:59:05.607127+00
8	\N	novaconta11407@teste.com	$argon2id$v=19$m=65536,t=3,p=4$ATbN6/MMkWHHVkXDy96qTg$en0C+ZAEdQHc2bgQ1Sv9p7O/d2y4a26Z9mjyvZQiq/s	2	2026-09-12 16:15:35.965043+00	2026-09-12 16:15:35.965043+00
9	\N	novaconta21742@teste.com	$argon2id$v=19$m=65536,t=3,p=4$hMNufLkZwZliMRN4vElvoA$2h0uAeDWQHd/s1Lts0dNJI9doiR7ghNwEJh+taBC/iw	2	2026-09-12 16:16:52.090977+00	2026-09-12 16:16:52.090977+00
10	\N	ms.mariaeduarda6755@gmail.com	$argon2id$v=19$m=65536,t=3,p=4$sn9H94frq8c2miP2MuRqSg$syDgIkuHihvcqS6E+hS31m7rlT2eWGfGDuzdvHe3Lws	2	2026-09-12 16:21:56.172231+00	2026-09-12 16:21:56.172231+00
11	\N	dudalina1323@gmail.com	$argon2id$v=19$m=65536,t=3,p=4$3EM7V29GtIXdgr7Yg+sdPg$9GH4hayxX/JpTfP3P2NlejEraUgY+RlWTHzOF9NAq4k	2	2026-09-13 04:39:40.735133+00	2026-09-13 04:39:40.735133+00
\.


--
-- Name: administradores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.administradores_id_seq', 2, true);


--
-- Name: agendamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.agendamentos_id_seq', 10, true);


--
-- Name: bloqueios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.bloqueios_id_seq', 1, false);


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.clientes_id_seq', 10, true);


--
-- Name: mensagens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.mensagens_id_seq', 1, false);


--
-- Name: modelos_unhas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.modelos_unhas_id_seq', 2, true);


--
-- Name: nail_designs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.nail_designs_id_seq', 1, true);


--
-- Name: notificacoes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.notificacoes_id_seq', 16, true);


--
-- Name: password_resets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.password_resets_id_seq', 2, true);


--
-- Name: programacao_semanal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.programacao_semanal_id_seq', 10, true);


--
-- Name: push_subscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.push_subscriptions_id_seq', 1, false);


--
-- Name: status_pagamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.status_pagamentos_id_seq', 3, true);


--
-- Name: type_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.type_users_id_seq', 1, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nail_admin
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 11, true);


--
-- Name: administradores administradores_email_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_email_key UNIQUE (email);


--
-- Name: administradores administradores_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_pkey PRIMARY KEY (id);


--
-- Name: agendamentos agendamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT agendamentos_pkey PRIMARY KEY (id);


--
-- Name: bloqueios bloqueios_data_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.bloqueios
    ADD CONSTRAINT bloqueios_data_key UNIQUE (data);


--
-- Name: bloqueios bloqueios_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.bloqueios
    ADD CONSTRAINT bloqueios_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: mensagens mensagens_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.mensagens
    ADD CONSTRAINT mensagens_pkey PRIMARY KEY (id);


--
-- Name: modelos_unhas modelos_unhas_nome_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.modelos_unhas
    ADD CONSTRAINT modelos_unhas_nome_key UNIQUE (nome);


--
-- Name: modelos_unhas modelos_unhas_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.modelos_unhas
    ADD CONSTRAINT modelos_unhas_pkey PRIMARY KEY (id);


--
-- Name: nail_designs nail_designs_cpf_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.nail_designs
    ADD CONSTRAINT nail_designs_cpf_key UNIQUE (cpf);


--
-- Name: nail_designs nail_designs_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.nail_designs
    ADD CONSTRAINT nail_designs_pkey PRIMARY KEY (id);


--
-- Name: notificacoes notificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_token_hash_key UNIQUE (token_hash);


--
-- Name: programacao_semanal programacao_semanal_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.programacao_semanal
    ADD CONSTRAINT programacao_semanal_pkey PRIMARY KEY (id);


--
-- Name: push_subscriptions push_subscriptions_endpoint_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint);


--
-- Name: push_subscriptions push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: status_pagamentos status_pagamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.status_pagamentos
    ADD CONSTRAINT status_pagamentos_pkey PRIMARY KEY (id);


--
-- Name: type_users type_users_nome_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.type_users
    ADD CONSTRAINT type_users_nome_key UNIQUE (nome);


--
-- Name: type_users type_users_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.type_users
    ADD CONSTRAINT type_users_pkey PRIMARY KEY (id);


--
-- Name: programacao_semanal uq_programacao_semanal_profissional_dia; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.programacao_semanal
    ADD CONSTRAINT uq_programacao_semanal_profissional_dia UNIQUE (profissional_id, dia_semana);


--
-- Name: status_pagamentos uq_status_pagamentos_nome; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.status_pagamentos
    ADD CONSTRAINT uq_status_pagamentos_nome UNIQUE (nome);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: ix_administradores_nail_design_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_administradores_nail_design_id ON public.administradores USING btree (nail_design_id);


--
-- Name: ix_agendamentos_cliente_data; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_cliente_data ON public.agendamentos USING btree (cliente_id, data);


--
-- Name: ix_agendamentos_cliente_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_cliente_id ON public.agendamentos USING btree (cliente_id);


--
-- Name: ix_agendamentos_data; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_data ON public.agendamentos USING btree (data);


--
-- Name: ix_agendamentos_data_horario; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_data_horario ON public.agendamentos USING btree (data, horario);


--
-- Name: ix_agendamentos_horario; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_horario ON public.agendamentos USING btree (horario);


--
-- Name: ix_agendamentos_pendentes; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_pendentes ON public.agendamentos USING btree (data, horario) WHERE (status_pagamentos_id = 2);


--
-- Name: ix_agendamentos_status_pagamentos_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_agendamentos_status_pagamentos_id ON public.agendamentos USING btree (status_pagamentos_id);


--
-- Name: ix_clientes_cpf; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_clientes_cpf ON public.clientes USING btree (cpf);


--
-- Name: ix_clientes_created_at; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_clientes_created_at ON public.clientes USING brin (created_at);


--
-- Name: ix_clientes_nome; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_clientes_nome ON public.clientes USING btree (nome);


--
-- Name: ix_clientes_nome_trgm; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_clientes_nome_trgm ON public.clientes USING gin (nome public.gin_trgm_ops);


--
-- Name: ix_clientes_telefone; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_clientes_telefone ON public.clientes USING btree (telefone);


--
-- Name: ix_mensagens_agendamento_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_mensagens_agendamento_id ON public.mensagens USING btree (agendamento_id);


--
-- Name: ix_mensagens_created_at; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_mensagens_created_at ON public.mensagens USING btree (created_at DESC);


--
-- Name: ix_modelos_unhas_ativo; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_modelos_unhas_ativo ON public.modelos_unhas USING btree (ativo) WHERE (ativo = true);


--
-- Name: ix_modelos_unhas_categoria; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_modelos_unhas_categoria ON public.modelos_unhas USING btree (categoria);


--
-- Name: ix_notificacoes_created_at; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_notificacoes_created_at ON public.notificacoes USING btree (created_at DESC);


--
-- Name: ix_notificacoes_lida; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_notificacoes_lida ON public.notificacoes USING btree (lida);


--
-- Name: ix_password_resets_usuario_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_password_resets_usuario_id ON public.password_resets USING btree (usuario_id);


--
-- Name: ix_programacao_semanal_profissional_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_programacao_semanal_profissional_id ON public.programacao_semanal USING btree (profissional_id);


--
-- Name: ix_usuarios_type_user_id; Type: INDEX; Schema: public; Owner: nail_admin
--

CREATE INDEX ix_usuarios_type_user_id ON public.usuarios USING btree (type_user_id);


--
-- Name: administradores fk_administradores_nail_design_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT fk_administradores_nail_design_id FOREIGN KEY (nail_design_id) REFERENCES public.nail_designs(id) ON DELETE SET NULL;


--
-- Name: administradores fk_administradores_type_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT fk_administradores_type_user_id FOREIGN KEY (type_user_id) REFERENCES public.type_users(id) ON DELETE RESTRICT;


--
-- Name: agendamentos fk_agendamentos_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT fk_agendamentos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE RESTRICT;


--
-- Name: agendamentos fk_agendamentos_modelo_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT fk_agendamentos_modelo_id FOREIGN KEY (modelo_id) REFERENCES public.modelos_unhas(id) ON DELETE RESTRICT;


--
-- Name: agendamentos fk_agendamentos_status_pagamentos_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT fk_agendamentos_status_pagamentos_id FOREIGN KEY (status_pagamentos_id) REFERENCES public.status_pagamentos(id) ON DELETE RESTRICT;


--
-- Name: clientes fk_clientes_email_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT fk_clientes_email_id FOREIGN KEY (email_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- Name: mensagens fk_mensagens_agendamento_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.mensagens
    ADD CONSTRAINT fk_mensagens_agendamento_id FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id) ON DELETE CASCADE;


--
-- Name: notificacoes fk_notificacoes_agendamento_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fk_notificacoes_agendamento_id FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id) ON DELETE SET NULL;


--
-- Name: password_resets fk_password_resets_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT fk_password_resets_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: programacao_semanal fk_programacao_semanal_profissional_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.programacao_semanal
    ADD CONSTRAINT fk_programacao_semanal_profissional_id FOREIGN KEY (profissional_id) REFERENCES public.nail_designs(id) ON DELETE CASCADE;


--
-- Name: usuarios fk_usuarios_type_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nail_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_type_user_id FOREIGN KEY (type_user_id) REFERENCES public.type_users(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict 9yc20c9gAeFUbITaU235JpNQnk8ffjccbXqGpD53FKN0RSjJL1mUdhuCgqlcrvs

