--
-- PostgreSQL database dump
--

\restrict 8UA7Cx8YE6mGxKIelzT2P4zAruM0DC7uHl48SOzRJcStQoWr3h31mO34j4TSBOq

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administradores; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.administradores (
    id integer NOT NULL,
    email character varying(255),
    password character varying(255),
    type_user_id integer,
    nome character varying(255)
);


ALTER TABLE public.administradores OWNER TO agendamento_admin;

--
-- Name: administradores_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.administradores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administradores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agendamentos; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.agendamentos (
    id integer NOT NULL,
    cliente_id integer,
    modelo integer,
    horario time without time zone,
    sinal numeric,
    status integer,
    data date
);


ALTER TABLE public.agendamentos OWNER TO agendamento_admin;

--
-- Name: agendamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.agendamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agendamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bloqueios; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.bloqueios (
    id bigint NOT NULL,
    data date NOT NULL,
    motivo character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.bloqueios OWNER TO agendamento_admin;

--
-- Name: bloqueios_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.bloqueios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bloqueios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.clientes (
    id integer NOT NULL,
    nome character varying(255),
    telefone character varying(255),
    email_id character varying(255),
    molde text,
    cpf character varying(14),
    data_nascimento date,
    pref_app boolean DEFAULT true NOT NULL,
    pref_email boolean DEFAULT true NOT NULL,
    pref_whatsapp boolean DEFAULT false NOT NULL
);


ALTER TABLE public.clientes OWNER TO agendamento_admin;

--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagens; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.mensagens (
    id bigint NOT NULL,
    agendamento_id bigint,
    remetente character varying(20) DEFAULT 'admin'::character varying NOT NULL,
    texto text NOT NULL,
    lida boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_mensagens_remetente CHECK (((remetente)::text = ANY ((ARRAY['admin'::character varying, 'cliente'::character varying])::text[])))
);


ALTER TABLE public.mensagens OWNER TO agendamento_admin;

--
-- Name: mensagens_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.mensagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modelos_unhas; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.modelos_unhas (
    id integer NOT NULL,
    nome character varying(255),
    valor_total numeric,
    categoria character varying(255),
    descricao character varying(255),
    duracao time without time zone,
    ativo boolean DEFAULT true NOT NULL,
    destaque boolean DEFAULT false NOT NULL,
    imagem_url text
);


ALTER TABLE public.modelos_unhas OWNER TO agendamento_admin;

--
-- Name: modelos_unhas_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.modelos_unhas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modelos_unhas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nails_designs; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.nails_designs (
    id integer NOT NULL,
    nome character varying(255),
    cpf character varying(255),
    telefone character varying(255)
);


ALTER TABLE public.nails_designs OWNER TO agendamento_admin;

--
-- Name: nails_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.nails_designs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nails_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificacoes; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.notificacoes (
    id bigint NOT NULL,
    tipo character varying(30) NOT NULL,
    titulo character varying(150) NOT NULL,
    mensagem text NOT NULL,
    agendamento_id bigint,
    lida boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_notificacoes_tipo CHECK (((tipo)::text = ANY ((ARRAY['agendamento'::character varying, 'cancelamento'::character varying, 'pagamento'::character varying, 'mensagem'::character varying])::text[])))
);


ALTER TABLE public.notificacoes OWNER TO agendamento_admin;

--
-- Name: notificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.notificacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_resets; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.password_resets (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    usado_em timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.password_resets OWNER TO agendamento_admin;

--
-- Name: password_resets_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.password_resets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_resets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: programacao_semanal; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.programacao_semanal (
    id integer NOT NULL,
    profissional_id integer,
    dia_da_semana integer,
    ativo boolean,
    inicio_expediente time without time zone,
    fim_expediente time without time zone,
    pausa_duracao integer,
    created_at date,
    updated_at date,
    intervalo_minutos integer DEFAULT 90 NOT NULL
);


ALTER TABLE public.programacao_semanal OWNER TO agendamento_admin;

--
-- Name: programacao_semanal_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.programacao_semanal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programacao_semanal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: push_subscriptions; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.push_subscriptions (
    id bigint NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.push_subscriptions OWNER TO agendamento_admin;

--
-- Name: push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status_pagamentos; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.status_pagamentos (
    id integer NOT NULL,
    nome character varying(255)
);


ALTER TABLE public.status_pagamentos OWNER TO agendamento_admin;

--
-- Name: status_pagamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.status_pagamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_pagamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_users; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.type_users (
    id integer NOT NULL,
    nome character varying(25) NOT NULL
);


ALTER TABLE public.type_users OWNER TO agendamento_admin;

--
-- Name: type_users_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

CREATE SEQUENCE public.type_users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.type_users_id_seq OWNER TO agendamento_admin;

--
-- Name: type_users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: agendamento_admin
--

ALTER SEQUENCE public.type_users_id_seq OWNED BY public.type_users.id;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: agendamento_admin
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    email character varying(255),
    password character varying(255),
    type_user_id integer,
    nome character varying(255)
);


ALTER TABLE public.usuarios OWNER TO agendamento_admin;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: agendamento_admin
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_users id; Type: DEFAULT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.type_users ALTER COLUMN id SET DEFAULT nextval('public.type_users_id_seq'::regclass);


--
-- Name: administradores administradores_nome_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_nome_key UNIQUE (nome);


--
-- Name: administradores administradores_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_pkey PRIMARY KEY (id);


--
-- Name: agendamentos agendamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT agendamentos_pkey PRIMARY KEY (id);


--
-- Name: bloqueios bloqueios_data_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.bloqueios
    ADD CONSTRAINT bloqueios_data_key UNIQUE (data);


--
-- Name: bloqueios bloqueios_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.bloqueios
    ADD CONSTRAINT bloqueios_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_nome_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_nome_key UNIQUE (nome);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: mensagens mensagens_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.mensagens
    ADD CONSTRAINT mensagens_pkey PRIMARY KEY (id);


--
-- Name: modelos_unhas modelos_unhas_nome_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.modelos_unhas
    ADD CONSTRAINT modelos_unhas_nome_key UNIQUE (nome);


--
-- Name: modelos_unhas modelos_unhas_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.modelos_unhas
    ADD CONSTRAINT modelos_unhas_pkey PRIMARY KEY (id);


--
-- Name: nails_designs nails_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.nails_designs
    ADD CONSTRAINT nails_pkey PRIMARY KEY (id);


--
-- Name: notificacoes notificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_pkey PRIMARY KEY (id);


--
-- Name: password_resets password_resets_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT password_resets_token_hash_key UNIQUE (token_hash);


--
-- Name: programacao_semanal programacao_semanal_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.programacao_semanal
    ADD CONSTRAINT programacao_semanal_pkey PRIMARY KEY (id);


--
-- Name: push_subscriptions push_subscriptions_endpoint_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint);


--
-- Name: push_subscriptions push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: status_pagamentos status_pagamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.status_pagamentos
    ADD CONSTRAINT status_pagamentos_pkey PRIMARY KEY (id);


--
-- Name: type_users type_users_nome_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.type_users
    ADD CONSTRAINT type_users_nome_key UNIQUE (nome);


--
-- Name: type_users type_users_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.type_users
    ADD CONSTRAINT type_users_pkey PRIMARY KEY (id);


--
-- Name: clientes unique_cpf; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT unique_cpf UNIQUE (cpf);


--
-- Name: clientes unique_nome; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT unique_nome UNIQUE (nome);


--
-- Name: usuarios usuarios_nome_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_nome_key UNIQUE (nome);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_username_key; Type: CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_username_key UNIQUE (email);


--
-- Name: ix_agendamentos_cliente_data; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_agendamentos_cliente_data ON public.agendamentos USING btree (cliente_id, data);


--
-- Name: ix_agendamentos_data; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_agendamentos_data ON public.agendamentos USING btree (data);


--
-- Name: ix_mensagens_agendamento_id; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_mensagens_agendamento_id ON public.mensagens USING btree (agendamento_id);


--
-- Name: ix_mensagens_created_at; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_mensagens_created_at ON public.mensagens USING btree (created_at DESC);


--
-- Name: ix_notificacoes_created_at; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_notificacoes_created_at ON public.notificacoes USING btree (created_at DESC);


--
-- Name: ix_notificacoes_lida; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_notificacoes_lida ON public.notificacoes USING btree (lida);


--
-- Name: ix_password_resets_usuario_id; Type: INDEX; Schema: public; Owner: agendamento_admin
--

CREATE INDEX ix_password_resets_usuario_id ON public.password_resets USING btree (usuario_id);


--
-- Name: agendamentos agendamentos_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT agendamentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- Name: agendamentos agendamentos_modelo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT agendamentos_modelo_fkey FOREIGN KEY (modelo) REFERENCES public.modelos_unhas(id);


--
-- Name: agendamentos agendamentos_status_fkey; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT agendamentos_status_fkey FOREIGN KEY (status) REFERENCES public.status_pagamentos(id);


--
-- Name: clientes clientes_username_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_username_id_fkey FOREIGN KEY (email_id) REFERENCES public.usuarios(email);


--
-- Name: administradores fk_administradores_type_user; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT fk_administradores_type_user FOREIGN KEY (type_user_id) REFERENCES public.type_users(id);


--
-- Name: agendamentos fk_agendamentos_status; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.agendamentos
    ADD CONSTRAINT fk_agendamentos_status FOREIGN KEY (status) REFERENCES public.status_pagamentos(id);


--
-- Name: mensagens fk_mensagens_agendamento_id; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.mensagens
    ADD CONSTRAINT fk_mensagens_agendamento_id FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id) ON DELETE CASCADE;


--
-- Name: notificacoes fk_notificacoes_agendamento_id; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fk_notificacoes_agendamento_id FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id) ON DELETE SET NULL;


--
-- Name: password_resets fk_password_resets_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.password_resets
    ADD CONSTRAINT fk_password_resets_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: usuarios fk_usuarios_type_user; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_type_user FOREIGN KEY (type_user_id) REFERENCES public.type_users(id);


--
-- Name: programacao_semanal programacao_semanal_profissional_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: agendamento_admin
--

ALTER TABLE ONLY public.programacao_semanal
    ADD CONSTRAINT programacao_semanal_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.nails_designs(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 8UA7Cx8YE6mGxKIelzT2P4zAruM0DC7uHl48SOzRJcStQoWr3h31mO34j4TSBOq

