-- =====================================================================
-- MIGRATION 001 — Modelo empresarial + type_users + Cloudflare R2
-- Idempotente: pode rodar várias vezes (psql -f 001_enterprise_schema.sql).
-- Traz bancos legados (modelagem_banco.sql / schema.sql antigo) para o
-- modelo canônico descrito em schema.sql (raiz do repo).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. TABELAS-BASE (banco fresco: cria o mínimo que o backend consulta)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "usuarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "clientes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "telefone" VARCHAR(30),
    "email_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "administradores" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT,
    "nail_design_id" BIGINT
);

CREATE TABLE IF NOT EXISTS "modelos_unhas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL UNIQUE,
    "valor_total" NUMERIC(10, 2),
    "categoria" VARCHAR(50),
    "descricao" TEXT,
    "duracao" TIME
);

CREATE TABLE IF NOT EXISTS "programacao_semanal" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profissional_id" BIGINT,
    "dia_semana" VARCHAR(20),
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "inicio_expediente" TIME,
    "fim_expediente" TIME,
    "pausa_duracao" TIME
);

CREATE TABLE IF NOT EXISTS "status_pagamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "agendamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cliente_id" BIGINT NOT NULL,
    "modelo_id" BIGINT NOT NULL,
    "horario" TIME NOT NULL,
    "sinal" NUMERIC(10, 2) NOT NULL,
    "status_pagamentos_id" BIGINT
);

-- ---------------------------------------------------------------------
-- 1. TYPE_USERS (nova) + seeds alinhados ao backend (ADMIN=1, USER=2)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "type_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(30) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO "type_users" ("id", "nome") VALUES
    (1, 'ADMIN'),
    (2, 'USER')
ON CONFLICT ("id") DO UPDATE SET
    "nome" = EXCLUDED."nome",
    "updated_at" = now();

-- ---------------------------------------------------------------------
-- 2. RENOMEIA TABELA LEGADA COM TYPO (nada a fazer se já correta)
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'nail_desings'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'nail_designs'
    ) THEN
        ALTER TABLE "nail_desings" RENAME TO "nail_designs";
    END IF;
END $$;

-- Garante a tabela de profissionais no padrão atual
CREATE TABLE IF NOT EXISTS "nail_designs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "telefone" VARCHAR(30),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 3. RENOMEIA COLUNAS COM TYPO (expediente)
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'programacao_semanal'
          AND column_name = 'inicio_espediente'
    ) THEN
        ALTER TABLE "programacao_semanal"
            RENAME COLUMN "inicio_espediente" TO "inicio_expediente";
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'programacao_semanal'
          AND column_name = 'fim_espediente'
    ) THEN
        ALTER TABLE "programacao_semanal"
            RENAME COLUMN "fim_espediente" TO "fim_expediente";
    END IF;
END $$;

-- ---------------------------------------------------------------------
-- 4. NOVAS COLUNAS (auditoria + R2 + campos que o backend já consulta)
-- ---------------------------------------------------------------------
-- Auditoria padrão em todas as tabelas de domínio
DO $$
DECLARE
    t TEXT;
    tabelas TEXT[] := ARRAY[
        'usuarios', 'clientes', 'nail_designs', 'administradores',
        'modelos_unhas', 'programacao_semanal', 'status_pagamentos',
        'agendamentos'
    ];
BEGIN
    FOREACH t IN ARRAY tabelas LOOP
        BEGIN
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN IF NOT EXISTS "created_at" '
                'TIMESTAMPTZ NOT NULL DEFAULT now()', t
            );
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN IF NOT EXISTS "updated_at" '
                'TIMESTAMPTZ NOT NULL DEFAULT now()', t
            );
        EXCEPTION WHEN others THEN
            RAISE NOTICE 'Auditoria pulada em %: %', t, SQLERRM;
        END;
    END LOOP;
END $$;

-- Foto do catálogo servida via Cloudflare R2 (api/storage/r2.py)
ALTER TABLE "modelos_unhas"
    ADD COLUMN IF NOT EXISTS "imagem_url" TEXT;

-- security.get_user_by_email seleciona usuarios.nome
ALTER TABLE "usuarios"
    ADD COLUMN IF NOT EXISTS "nome" VARCHAR(100);

-- programacao_semanal.profissional_id (usado em filtros e UNIQUE)
ALTER TABLE "programacao_semanal"
    ADD COLUMN IF NOT EXISTS "profissional_id" BIGINT;

-- administradores.type_user_id padronizado como BIGINT
DO $$
BEGIN
    BEGIN
        ALTER TABLE "administradores"
            ALTER COLUMN "type_user_id" TYPE BIGINT;
    EXCEPTION WHEN others THEN
        -- coluna ausente ou com dados incompatíveis: cria do zero
        ALTER TABLE "administradores"
            ADD COLUMN IF NOT EXISTS "type_user_id" BIGINT;
    END;
END $$;

-- clientes.email_id referencia usuarios(id): Revolve para BIGINT
DO $$
BEGIN
    BEGIN
        ALTER TABLE "clientes"
            ALTER COLUMN "email_id" TYPE BIGINT
            USING "email_id"::BIGINT;
    EXCEPTION WHEN others THEN
        RAISE NOTICE 'email_id mantido como está (dados legados não conversíveis)';
    END;
END $$;

-- ---------------------------------------------------------------------
-- 5. FKs LEGADAS ERRADAS → FKs NOMEADAS CORRETAS
-- Remove FKs auto-nomeadas herdadas da modelagem antiga e recria no
-- padrão fk_<tabela>_<coluna> apontando para a tabela/coluna certas.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    fk TEXT;
    tbl TEXT;
    fks_legadas TEXT[] := ARRAY[
        'usuarios_email_fkey',
        'clientes_email_id_fkey',
        'clientes_id_fkey',
        'modelos_unhas_id_fkey',
        'status_pagamentos_id_fkey',
        'nails_id_fkey',
        'fk_administradores_type_user',
        'fk_usuarios_type_user'
    ];
BEGIN
    FOREACH fk IN ARRAY fks_legadas LOOP
        SELECT c.relname INTO tbl FROM pg_constraint k
        JOIN pg_class c ON c.oid = k.conrelid
        WHERE k.conname = fk LIMIT 1;
        IF tbl IS NOT NULL THEN
            BEGIN
                EXECUTE format(
                    'ALTER TABLE %I DROP CONSTRAINT %I', tbl, fk
                );
            EXCEPTION WHEN others THEN
                RAISE NOTICE 'FK % pulada: %', fk, SQLERRM;
            END;
        END IF;
    END LOOP;
END $$;

-- Recria as FKs no padrão (só se coluna e alvo existirem eTipos)
DO $$
BEGIN
    -- usuarios.type_user_id → type_users(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuarios_type_user_id'
    ) THEN
        ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_type_user_id"
            FOREIGN KEY ("type_user_id") REFERENCES "type_users" ("id")
            ON UPDATE NO ACTION ON DELETE RESTRICT;
    END IF;

    -- administradores.type_user_id → type_users(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_administradores_type_user_id'
    ) THEN
        ALTER TABLE "administradores"
            ADD CONSTRAINT "fk_administradores_type_user_id"
            FOREIGN KEY ("type_user_id") REFERENCES "type_users" ("id")
            ON UPDATE NO ACTION ON DELETE RESTRICT;
    END IF;

    -- administradores.nail_design_id → nail_designs(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_administradores_nail_design_id'
    ) THEN
        ALTER TABLE "administradores"
            ADD CONSTRAINT "fk_administradores_nail_design_id"
            FOREIGN KEY ("nail_design_id") REFERENCES "nail_designs" ("id")
            ON UPDATE NO ACTION ON DELETE SET NULL;
    END IF;

    -- programacao_semanal.profissional_id → nail_designs(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_programacao_semanal_profissional_id'
    ) THEN
        ALTER TABLE "programacao_semanal"
            ADD CONSTRAINT "fk_programacao_semanal_profissional_id"
            FOREIGN KEY ("profissional_id")
            REFERENCES "nail_designs" ("id")
            ON UPDATE NO ACTION ON DELETE CASCADE;
    END IF;

    -- agendamentos.cliente_id → clientes(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_agendamentos_cliente_id'
    ) THEN
        ALTER TABLE "agendamentos" ADD CONSTRAINT "fk_agendamentos_cliente_id"
            FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id")
            ON UPDATE NO ACTION ON DELETE RESTRICT;
    END IF;

    -- agendamentos.modelo_id → modelos_unhas(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_agendamentos_modelo_id'
    ) THEN
        ALTER TABLE "agendamentos" ADD CONSTRAINT "fk_agendamentos_modelo_id"
            FOREIGN KEY ("modelo_id") REFERENCES "modelos_unhas" ("id")
            ON UPDATE NO ACTION ON DELETE RESTRICT;
    END IF;

    -- agendamentos.status_pagamentos_id → status_pagamentos(id)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_agendamentos_status_pagamentos_id'
    ) THEN
        ALTER TABLE "agendamentos"
            ADD CONSTRAINT "fk_agendamentos_status_pagamentos_id"
            FOREIGN KEY ("status_pagamentos_id")
            REFERENCES "status_pagamentos" ("id")
            ON UPDATE NO ACTION ON DELETE RESTRICT;
    END IF;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'FKs parcialmente aplicadas (dados legados?): %', SQLERRM;
END $$;

-- ---------------------------------------------------------------------
-- 6. ÍNDICES E UNIQUES DO PADRÃO
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "ix_usuarios_type_user_id"
    ON "usuarios" ("type_user_id");
CREATE INDEX IF NOT EXISTS "ix_clientes_email_id"
    ON "clientes" ("email_id");
CREATE INDEX IF NOT EXISTS "ix_clientes_nome"
    ON "clientes" ("nome");
CREATE INDEX IF NOT EXISTS "ix_administradores_nail_design_id"
    ON "administradores" ("nail_design_id");
CREATE INDEX IF NOT EXISTS "ix_modelos_unhas_categoria"
    ON "modelos_unhas" ("categoria");
CREATE INDEX IF NOT EXISTS "ix_programacao_semanal_profissional_id"
    ON "programacao_semanal" ("profissional_id");
CREATE INDEX IF NOT EXISTS "ix_agendamentos_cliente_id"
    ON "agendamentos" ("cliente_id");
CREATE INDEX IF NOT EXISTS "ix_agendamentos_status_pagamentos_id"
    ON "agendamentos" ("status_pagamentos_id");
CREATE INDEX IF NOT EXISTS "ix_agendamentos_horario"
    ON "agendamentos" ("horario");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_programacao_semanal_profissional_dia'
    ) THEN
        ALTER TABLE "programacao_semanal"
            ADD CONSTRAINT "uq_programacao_semanal_profissional_dia"
            UNIQUE ("profissional_id", "dia_semana");
    END IF;
EXCEPTION WHEN others THEN
    RAISE NOTICE 'UNIQUE pulado (duplicados legados?): %', SQLERRM;
END $$;

-- ---------------------------------------------------------------------
-- 7. SEED DE STATUS (o backend espera Pendente/Pago/Cancelado)
-- Sem ON CONFLICT: bancos legados podem não ter UNIQUE em nome.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    BEGIN
        ALTER TABLE "status_pagamentos"
            ADD CONSTRAINT "uq_status_pagamentos_nome" UNIQUE ("nome");
    EXCEPTION WHEN duplicate_object THEN
        -- já existe
    WHEN others THEN
        RAISE NOTICE 'UNIQUE de status pulada (duplicados legados?): %', SQLERRM;
    END;

    INSERT INTO "status_pagamentos" ("nome")
    SELECT s.nome FROM (VALUES ('Pendente'), ('Pago'), ('Cancelado')) AS s(nome)
    WHERE NOT EXISTS (
        SELECT 1 FROM "status_pagamentos" sp WHERE sp.nome = s.nome
    );
END $$;
