-- =====================================================================
-- MIGRATION 002 — Central de notificações do painel admin + Web Push
-- Idempotente: pode rodar várias vezes (psql -f 002_notificacoes_push.sql).
--   * notificacoes: mural do sino no painel (agendamento, cancelamento,
--     pagamento; mensagens entram quando o backend de mensagens existir)
--   * push_subscriptions: inscrições Web Push dos dispositivos logados
-- =====================================================================

CREATE TABLE IF NOT EXISTS "notificacoes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" VARCHAR(30) NOT NULL,
    "titulo" VARCHAR(150) NOT NULL,
    "mensagem" TEXT NOT NULL,
    "agendamento_id" BIGINT
        CONSTRAINT "fk_notificacoes_agendamento_id"
        REFERENCES "agendamentos" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "lida" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "ck_notificacoes_tipo" CHECK (
        "tipo" IN ('agendamento', 'cancelamento', 'pagamento', 'mensagem')
    )
);
CREATE INDEX IF NOT EXISTS "ix_notificacoes_lida"
    ON "notificacoes" ("lida");
CREATE INDEX IF NOT EXISTS "ix_notificacoes_created_at"
    ON "notificacoes" ("created_at" DESC);

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "endpoint" TEXT NOT NULL UNIQUE,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
