-- =====================================================================
-- MIGRATION 003 — Molde do cliente, intervalo da agenda, mensagens e bloqueios
-- Idempotente: pode rodar várias vezes (psql -f 003_molde_mensagens_bloqueios.sql).
-- =====================================================================

-- Molde da unha da cliente (RN05 — editável só pela profissional)
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "molde" TEXT;

-- Intervalo entre slots configurável por dia (RF27)
ALTER TABLE "programacao_semanal"
    ADD COLUMN IF NOT EXISTS "intervalo_minutos" INTEGER NOT NULL DEFAULT 90;

-- Mensagens admin ⇄ cliente (RF16, RF23, RF25)
CREATE TABLE IF NOT EXISTS "mensagens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "agendamento_id" BIGINT
        CONSTRAINT "fk_mensagens_agendamento_id"
        REFERENCES "agendamentos" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE,
    "remetente" VARCHAR(20) NOT NULL DEFAULT 'admin',
    "texto" TEXT NOT NULL,
    "lida" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "ck_mensagens_remetente" CHECK (
        "remetente" IN ('admin', 'cliente')
    )
);
CREATE INDEX IF NOT EXISTS "ix_mensagens_agendamento_id"
    ON "mensagens" ("agendamento_id");
CREATE INDEX IF NOT EXISTS "ix_mensagens_created_at"
    ON "mensagens" ("created_at" DESC);

-- Bloqueios e exceções de agenda (dias fechados, feriados, cursos)
CREATE TABLE IF NOT EXISTS "bloqueios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "data" DATE NOT NULL UNIQUE,
    "motivo" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
