-- =====================================================================
-- MIGRATION 005 — Recuperação de senha, visibilidade do catálogo e
-- dados cadastrais completos
-- Idempotente: pode rodar várias vezes (psql -f 005_reset_e_campos.sql).
-- =====================================================================

-- Tokens de redefinição de senha (RF03) — guarda só o hash, uso único
CREATE TABLE IF NOT EXISTS "password_resets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "usuario_id" BIGINT NOT NULL
        CONSTRAINT "fk_password_resets_usuario_id"
        REFERENCES "usuarios" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE,
    "token_hash" VARCHAR(255) NOT NULL UNIQUE,
    "expira_em" TIMESTAMPTZ NOT NULL,
    "usado_em" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "ix_password_resets_usuario_id"
    ON "password_resets" ("usuario_id");

-- Visibilidade e destaque no catálogo (telas admin/cliente)
ALTER TABLE "modelos_unhas"
    ADD COLUMN IF NOT EXISTS "ativo" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "modelos_unhas"
    ADD COLUMN IF NOT EXISTS "destaque" BOOLEAN NOT NULL DEFAULT FALSE;

-- Dados cadastrais completos da cliente
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "cpf" VARCHAR(14);
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "data_nascimento" DATE;
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "pref_app" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "pref_email" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "clientes"
    ADD COLUMN IF NOT EXISTS "pref_whatsapp" BOOLEAN NOT NULL DEFAULT FALSE;
