/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as MeusDadosRouteImport } from './routes/meus-dados'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendamentosRouteImport } from './routes/admin/agendamentos'
import { Route as AdminCatalogoRouteImport } from './routes/admin/catalogo'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminHorariosRouteImport } from './routes/admin/horarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusDadosRoute = MeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/admin/agendamentos',
  path: '/admin/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/admin/catalogo',
  path: '/admin/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/admin/horarios',
  path: '/admin/horarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/catalogo': typeof CatalogoRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/catalogo': typeof CatalogoRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/catalogo': typeof CatalogoRoute
  '/mensagens': typeof MensagensRoute
  '/meus-dados': typeof MeusDadosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/catalogo'
    | '/mensagens'
    | '/meus-dados'
    | '/redefinir-senha'
    | '/admin/agendamentos'
    | '/admin/catalogo'
    | '/admin/clientes'
    | '/admin/horarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/catalogo'
    | '/mensagens'
    | '/meus-dados'
    | '/redefinir-senha'
    | '/admin/agendamentos'
    | '/admin/catalogo'
    | '/admin/clientes'
    | '/admin/horarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/catalogo'
    | '/mensagens'
    | '/meus-dados'
    | '/redefinir-senha'
    | '/admin/agendamentos'
    | '/admin/catalogo'
    | '/admin/clientes'
    | '/admin/horarios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  CatalogoRoute: typeof CatalogoRoute
  MensagensRoute: typeof MensagensRoute
  MeusDadosRoute: typeof MeusDadosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-dados': {
      id: '/meus-dados'
      path: '/meus-dados'
      fullPath: '/meus-dados'
      preLoaderRoute: typeof MeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/admin/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/admin/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  CatalogoRoute: CatalogoRoute,
  MensagensRoute: MensagensRoute,
  MeusDadosRoute: MeusDadosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
