-- =====================================================================
-- MODELAGEM DO BANCO — Ana Clara Nails (documento de referência)
-- Fonte única de verdade do DDL: schema.sql (raiz do repo).
-- Migrações incrementais: back/migrations/.
-- Convenção: FKs nomeadas fk_<tabela>_<coluna>, sempre da tabela filha
-- (que tem a coluna) para a tabela pai (dono da PK).
-- =====================================================================

CREATE TABLE IF NOT EXISTS "type_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(30) NOT NULL UNIQUE,               -- 'ADMIN' | 'USER'
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "usuarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100),
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT NOT NULL
        CONSTRAINT "fk_usuarios_type_user_id"
        REFERENCES "type_users" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "clientes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "telefone" VARCHAR(30),
    "email_id" BIGINT
        CONSTRAINT "fk_clientes_email_id"
        REFERENCES "usuarios" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "nail_designs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "cpf" VARCHAR(14) NOT NULL UNIQUE,
    "telefone" VARCHAR(30),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "administradores" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "type_user_id" BIGINT NOT NULL
        CONSTRAINT "fk_administradores_type_user_id"
        REFERENCES "type_users" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "nail_design_id" BIGINT
        CONSTRAINT "fk_administradores_nail_design_id"
        REFERENCES "nail_designs" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "modelos_unhas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(100) NOT NULL UNIQUE,
    "valor_total" NUMERIC(10, 2) NOT NULL,
    "categoria" VARCHAR(50),
    "descricao" TEXT,
    "duracao" TIME,
    "imagem_url" TEXT,                                -- foto servida via Cloudflare R2
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "programacao_semanal" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profissional_id" BIGINT NOT NULL
        CONSTRAINT "fk_programacao_semanal_profissional_id"
        REFERENCES "nail_designs" ("id")
        ON UPDATE NO ACTION ON DELETE CASCADE,
    "dia_semana" VARCHAR(20) NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "inicio_expediente" TIME,
    "fim_expediente" TIME,
    "pausa_duracao" TIME,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_programacao_semanal_profissional_dia"
        UNIQUE ("profissional_id", "dia_semana")
);

CREATE TABLE IF NOT EXISTS "status_pagamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(30) NOT NULL UNIQUE,               -- Pendente | Pago | Cancelado
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "agendamentos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cliente_id" BIGINT NOT NULL
        CONSTRAINT "fk_agendamentos_cliente_id"
        REFERENCES "clientes" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "modelo_id" BIGINT NOT NULL
        CONSTRAINT "fk_agendamentos_modelo_id"
        REFERENCES "modelos_unhas" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "horario" TIME NOT NULL,
    "sinal" NUMERIC(10, 2) NOT NULL,                  -- RN01: 50% do valor_total
    "status_pagamentos_id" BIGINT
        CONSTRAINT "fk_agendamentos_status_pagamentos_id"
        REFERENCES "status_pagamentos" ("id")
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "notificacoes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" VARCHAR(30) NOT NULL,
    "titulo" VARCHAR(150) NOT NULL,
    "mensagem" TEXT NOT NULL,
    "agendamento_id" BIGINT
        CONSTRAINT "fk_notificacoes_agendamento_id"
        REFERENCES "agendamentos" ("id")
        ON UPDATE NO ACTION ON DELETE SET NULL,
    "lida" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "ck_notificacoes_tipo" CHECK (
        "tipo" IN ('agendamento', 'cancelamento', 'pagamento', 'mensagem')
    )
);

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "endpoint" TEXT NOT NULL UNIQUE,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- MAPA DE RELACIONAMENTOS (filha.coluna → pai.coluna)
--   usuarios.type_user_id        → type_users.id              (N:1)
--   clientes.email_id            → usuarios.id                (N:1)
--   administradores.type_user_id → type_users.id              (N:1)
--   administradores.nail_design_id → nail_designs.id          (N:1)
--   programacao_semanal.profissional_id → nail_designs.id    (N:1)
--   agendamentos.cliente_id      → clientes.id                (N:1)
--   agendamentos.modelo_id       → modelos_unhas.id           (N:1)
--   agendamentos.status_pagamentos_id → status_pagamentos.id (N:1)
--   notificacoes.agendamento_id  → agendamentos.id            (N:1)
-- ---------------------------------------------------------------------
